# frozen_string_literal: true

TELEMETRY_CHANGED_FILES_MESSAGE = <<~MSG
This merge request adds or changes files for which a
review from the Data team and Telemetry team is recommended.
@gitlab-org/growth/telemetry group is mentioned in order to notify team members.
MSG

usage_data_changed_files = git.modified_files.grep(%r{usage_data})

if usage_data_changed_files.any?
  warn format(TELEMETRY_CHANGED_FILES_MESSAGE)

  USAGE_DATA_FILES_MESSAGE = <<~MSG
  For the following files, a review from the [Data team and Telemetry team](https://gitlab.com/groups/gitlab-org/growth/telemetry/-/group_members?with_inherited_permissions=exclude) is recommended:
  MSG

  markdown(USAGE_DATA_FILES_MESSAGE + helper.markdown_list(usage_data_changed_files))

  telemetry_label = 'telemetry'

  unless gitlab.mr_labels.include?(telemetry_label)
    gitlab.api.update_merge_request(gitlab.mr_json['project_id'],
                                        gitlab.mr_json['iid'],
                                        labels: (gitlab.mr_labels + [telemetry_label]).join(','))
  end

  unless gitlab.mr_labels.include?('telemetry::reviewed')
    telemetry_pending_label = 'telemetry::review pending'

    gitlab.api.update_merge_request(gitlab.mr_json['project_id'],
                                        gitlab.mr_json['iid'],
                                        labels: (gitlab.mr_labels + [telemetry_pending_label]).join(','))
  end
end
