# frozen_string_literal: true

gitlab_danger = GitlabDanger.new(helper.gitlab_helper)

TELEMETRY_CHANGED_FILES_MESSAGE = <<~MSG
For this merge request it is recommended a telemetry and a data review. To make sure these
changes are reviewed, take the following steps:

1. Assign and mention a [telemetry reviewer](https://gitlab.com/groups/gitlab-org/growth/telemetry/-/group_members?with_inherited_permissions=exclude).
1. Assign and mention a data reviewer.
MSG

usage_data_changed_files = git.modified_files.grep(%r{usage_data})

if usage_data_changed_files.any?
  warn format(TELEMETRY_CHANGED_FILES_MESSAGE)
end

return unless gitlab_danger.ci?

if usage_data_changed_files.any?
  MESSAGE = <<~MSG
  This merge request adds or changes files that require a
  review from the Data team and
  Telemetry team @/gitlab-org/growth/telemetry
  The specific groups are mentioned in order to send a notification to team members.
  MSG

  USAGE_DATA_FILES_MESSAGE = <<~MSG
  The following files require a review from the Data team and Telemetry team:
  MSG

  markdown(MESSAGE)
  markdown(USAGE_DATA_FILES_MESSAGE + helper.markdown_list(usage_data_changed_files))
end
