# frozen_string_literal: true

gitlab_danger = GitlabDanger.new(helper.gitlab_helper)

TELEMETRY_CHANGED_FILES_MESSAGE = <<~MSG
This merge request requires a telemetry review. To make sure these
changes are reviewed, take the following steps: 
MSG

usage_data_changed_files = git.modified_files.grep(%{usage_data})

if usage_data_changed_files.any?
  warn format(TELEMETRY_CHANGED_FILES_MESSAGE)
end

return unless gitlab_danger.ci?

if usage_data_changed_files.any?
  MESSAGE = <<~MSG
  This merge request adds or changes files that require a
  review from the Data team and Telemetry team
  MSG

  USAGE_DATA_FILES_MESSAGE = <<~MSG
  The following files require a review from the Data team and Telemetry team:
  MSG

  markdown(MESSAGE)
  markdown(USAGE_DATA_FILES_MESSAGE + helper.markdown_list(usage_data_changed_files))
end